image: docker:latest
stages:
  - lint
  - dependencies_install
  - test
  - deploy
  - deploy-k8s

lint:
  stage: lint
  image: node:latest
  script:
    - npm install -g eslint
    - npm run lint

dependencies_install:
  stage: dependencies_install
  image: node:latest
  script:
    - if [[ ! -d node_modules ]] || [[ -n `git diff --name-only HEAD~1 HEAD | grep "\package.json\b"` ]];
      then
      npm install;
      fi
  cache:
    key:
      files:
        - package.json
    paths:
    - node_modules/

test:
  stage: test
  image: node:16.13.1
  cache:
    key:
      files:
        - package.json
    paths:
      - node_modules/
    policy: pull
  before_script:
    - echo NODE=develop >> .env
    - echo TELEGRAM_TEST_BOT_TOKEN=$TELEGRAM_TEST_BOT_TOKEN >> .env
    - echo TELEGRAM_TEST_USERID=$TELEGRAM_TEST_USERID >> .env
  script:
    - npm run test

Deploy:
  stage: deploy
  image: "docker:18.09"
  services:
    - docker:18-dind
  before_script:
    - chmod +x ./setup_env.sh
    - ./setup_env.sh
    - apk -Uuv add curl bash python
    - curl https://sdk.cloud.google.com | CLOUDSDK_CORE_DISABLE_PROMPTS=1 bash
    - export PATH=$PATH:/root/google-cloud-sdk/bin/
    - echo "$GCP_SERVICE_KEY" > gcloud-service-key.json # Google Cloud service accounts
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud auth configure-docker --quiet
    - docker login -u _json_key --password-stdin https://gcr.io < gcloud-service-key.json
  script:
    - docker build -t gcr.io/$GCP_PROJECT_ID/$IMAGE:$CI_PIPELINE_ID .
    - docker push gcr.io/$GCP_PROJECT_ID/$IMAGE:$CI_PIPELINE_ID
  only:
    - master

Deploy-k8s:
  image: google/cloud-sdk
  stage: deploy-k8s
  before_script:
    - echo "$GCP_SERVICE_KEY" > gcloud-service-key.json # Google Cloud service accounts
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud container clusters get-credentials $CLUSTER --zone $ZONE --project $GCP_PROJECT_ID
  script:
    - kubectl set image deployment $DEPLOYMENT $CONTAINER=gcr.io/$GCP_PROJECT_ID/$IMAGE:$CI_PIPELINE_ID
  dependencies:
    - Deploy
