image: docker:latest
stages:
  - deploy
  - deploy-k8s
Deploy:
  stage: deploy
  image: google/cloud-sdk
  before_script:
    - echo "$GCP_SERVICE_KEY" > gcloud-service-key.json # Google Cloud service accounts
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
  script:
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud builds submit --tag gcr.io/$GCP_PROJECT_ID/$IMAGE:$CI_PIPELINE_ID
  only:
    - master

Deploy-k8s:
  image: google/cloud-sdk
  stage: deploy-k8s
  before_script:
    - echo "$GCP_SERVICE_KEY" > gcloud-service-key.json # Google Cloud service accounts
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud container clusters get-credentials $CLUSTER --zone $ZONE --project $GCP_PROJECT_ID
  script:
    - kubectl set image deployment $DEPLOYMENT $CONTAINER=gcr.io/$GCP_PROJECT_ID/$IMAGE:$CI_PIPELINE_ID
  dependencies:
    - Deploy
